### ISSUE TITLE
why ekiden is empty

### ISSUE THREAD

**Issue by ldwaiwai** [ekiden/contract-dpcs#1]
I download the project, but ekiden is empty

**Comment by nhynes** [comment]
That's because `ekiden` is a [Git submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules). You'd need to do `git clone --recursive` or `git submodule update --init` to fetch it. Unfortunately that won't work because the `ekiden` dependency isn't available to be fetched.

Thanks for your interest in this repo, though! If you could describe what you're trying to do, perhaps we could try to provide an alternative solution.
